### ISSUE TITLE
Support `ChainExpression` AST node type for optional chaining

### ISSUE THREAD

**Issue by junoatscroll** [jsx-eslint/jsx-ast-utils#103]
## Symptom:
Began seeing `The prop value with an expression type of ChainExpression could not be resolved. Please file issue to get this fixed immediately.` in eslint output after upgrading.

ECMAscript Optional Chaining shipped, resulting in various changes to parsers and javascript/typescript tools to support it. Initially there were different, non-standard names for the AST nodes to represent it. Over this year, consensus has settled out, including in the parser that eslint uses, estree (see https://github.com/estree/estree/pull/204 ).

jsx-ast-utils should be updated to support the new AST nodes.

## Versions:
eslint@7.10.0
jsx-ast-utils@2.4.1 (via eslint-plugin-react@7.21.3, eslint-plugin-jsx-a11y@6.3.1)

## Minimal test case
Component.jsx
```
import React from 'react';

export function Component() {
  const x = {};
  return (
    <div role="button" key={x.y?.z}>
      hi
    </div>
  );
}

```

.eslintrc
```
module.exports = {
  extends: [
    'plugin:react/recommended',
    'plugin:jsx-a11y/recommended'
  ],
  plugins: ['react', 'jsx-a11y'],
}
```

run
```
eslint ./Component.jsx
```

## Related:
- #98
- https://github.com/estree/estree/pull/204 - parser spec change
- https://github.com/eslint/eslint/pull/13416 - support added in eslint 7.5.0
- https://github.com/facebook/react/issues/19940 - google search result

Example AST (via console.log):
```
{
  type: 'JSXExpressionContainer',
  expression: {
    type: 'ChainExpression',
    expression: {
      type: 'MemberExpression',
      object: [Object],
      property: [Object],
      computed: false,
      optional: true,
      range: [Array],
      loc: [Object],
      parent: [Circular]
    },
    range: [ 6299, 6313 ],
    loc: { start: [Object], end: [Object] },
    parent: [Circular]
  },
  range: [ 6298, 6314 ],
  loc: { start: { line: 205, column: 29 }, end: { line: 205, column: 45 } },
  parent: {
    type: 'JSXAttribute',
    name: {
      type: 'JSXIdentifier',
      name: 'href',
      range: [Array],
      loc: [Object],
      parent: [Circular]
    },
    value: [Circular],
    range: [ 6293, 6314 ],
    loc: { start: [Object], end: [Object] },
    parent: {
      type: 'JSXOpeningElement',
      typeParameters: undefined,
      selfClosing: false,
      name: [Object],
      attributes: [Array],
      range: [Array],
      loc: [Object],
      parent: [Object]
    }
  }
}
```

**Comment by ljharb** [comment]
See #102.
