### ISSUE TITLE
The prop value with an expression type of JSXEmptyExpression could not be resolved. Please file issue to get this fixed immediately.

### ISSUE THREAD

**Issue by ffMathy** [jsx-eslint/jsx-ast-utils#107]
The prop value with an expression type of JSXEmptyExpression could not be resolved. Please file issue to get this fixed immediately.

**Comment by ljharb** [comment]
Can you provide the code you used to get this error?

**Comment by ljharb** [comment]
Tests seem to pass with this expression type, so I'll close this for now.

If there's still a code sample that can reproduce the issue, I'm happy to reopen this and fix it.
