### ISSUE TITLE
TSNonNullExpression & JSXFragment: The prop value with an expression type of <type> could not be resolved. Please file issue to get this fixed immediately.

### ISSUE THREAD

**Issue by AriPerkkio** [jsx-eslint/jsx-ast-utils#108]
Hello, I'm seeing these errors while testing `eslint-plugin-jsx-a11y`. I believe these warnings are coming from this project. 

```
The prop value with an expression type of TSNonNullExpression could not be resolved. Please file issue to get this fixed immediately.
The prop value with an expression type of JSXFragment could not be resolved. Please file issue to get this fixed immediately.
```

https://github.com/AriPerkkio/eslint-remote-tester/runs/1542824521?check_suite_focus=true

I'm not exactly sure which code block or project is causing these. Is this info helpful enough to reproduce this or should I try to debug this closer? 

Also it would be great if this error message could contain stack trace. Any ideas why it's not currently included?

https://github.com/jsx-eslint/jsx-ast-utils/blob/4576cde302cd8b9ef40b6dc026b20cb005f2dbea/src/values/expressions/index.js#L99-L102

**Comment by ljharb** [comment]
@AriPerkkio thanks for the report! It'd be most helpful if you had code that could reproduce the TSNonNullExpression issue. I can handle the `<>` issue.

**Comment by AriPerkkio** [comment]
Here's minimal repro:

```ts
import React from "react";

class MyLink extends React.Component {
  render() {
    return <a href={this.props.href!}>Download</a>;
  }
}
```
