### ISSUE TITLE
The prop value with an expression type of JSXFragment could not be resolved

### ISSUE THREAD

**Issue by ondrejsevcik** [jsx-eslint/jsx-ast-utils#116]
Hi, 

I got this error while running ESLint on our code-base. Not sure where it is coming from though. 

```
The prop value with an expression type of JSXFragment could not be resolved. Please file an issue to get this fixed immediately.
```

```
@typescript-eslint/eslint-plugin: 5.18.0 
@typescript-eslint/parser: 5.18.0
eslint: 8.12.0
jsx-ast-utils: 3.2.1
node: v16.8.0
```

Hope this helps to fix the issue.

**Comment by ondrejsevcik** [comment]
That would be `jsx-ast-utils@3.2.1`

**Comment by ljharb** [comment]
If there's any way you could narrow down which code/file is causing the failure, that would help a ton.

(and you're sure that `npm ls | grep jsx-ast-utils` only returns v3.2.1?)

**Comment by ondrejsevcik** [comment]
This is output of `npm why jsx-ast-utils`

```
jsx-ast-utils@3.2.1 dev
node_modules/jsx-ast-utils
  jsx-ast-utils@"^3.2.1" from eslint-plugin-jsx-a11y@6.5.1
  node_modules/eslint-plugin-jsx-a11y
    dev eslint-plugin-jsx-a11y@"^6.5.1" from the root project
    peer eslint-plugin-jsx-a11y@"^6.5.1" from eslint-config-airbnb@19.0.4
    node_modules/eslint-config-airbnb
      dev eslint-config-airbnb@"^19.0.4" from the root project
  jsx-ast-utils@"^2.4.1 || ^3.0.0" from eslint-plugin-react@7.29.4
  node_modules/eslint-plugin-react
    dev eslint-plugin-react@"^7.29.4" from the root project
    peer eslint-plugin-react@"^7.28.0" from eslint-config-airbnb@19.0.4
    node_modules/eslint-config-airbnb
      dev eslint-config-airbnb@"^19.0.4" from the root project
```

**Comment by ondrejsevcik** [comment]
I've created reproduction repo https://github.com/ondrejsevcik/jsx-fragment-issue-repo

when you run `npm run lint` you should run into that issue as well. Hopefully this helps.

**Comment by ljharb** [comment]
When I run `npm install && npm run lint`, it works fine (it has some linting errors; the config needs to extend `plugin:react/jsx-runtime` and set indent and react/jsx-indent to 4, plus some others).

**Comment by ondrejsevcik** [comment]
> When I run npm install && npm run lint, it works fine (it has some linting errors; the config needs to extend plugin:react/jsx-runtime and set indent and react/jsx-indent to 4, plus some others).

I see those lint errors as well, but I thought it's not that important to fix them for this issue. The problem with parsing JSXFragment is still there.

> although, i'm using jsx-ast-utils v3.2.2 which has some TS-related fixes; can you try that?

The reproduction repo is using also v3.2.2.

**Comment by ljharb** [comment]
I’m not sure why i don’t see the parsing error in your repo, but you do. What node and npm version are you using?

**Comment by ondrejsevcik** [comment]
That's indeed strange. 

```
node: v16.8.0
npm: 7.21.0
```

<img width="1733" alt="image" src="https://user-images.githubusercontent.com/4136929/165902590-9aba5b4b-d519-4727-8f94-54c08fcf7f50.png">

**Comment by ljharb** [comment]
ahh i do see it, thanks.

**Comment by ondrejsevcik** [comment]
Thank you for a quick fix 👍🏽
