### ISSUE TITLE
Invitation to move to official `eslint-community` org

### ISSUE THREAD

**Issue by MichaelDeBoey** [jsx-eslint/jsx-ast-utils#121]
It's up to you —@ljharb—, but if you'd like, you're welcome to transfer this repository to the official [`@eslint-community` organization on GitHub](https://github.com/eslint-community).

As you can read in [the '`@eslint-community` GitHub organization' RFC](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org), the goal of this new org is to have a place where community members can help ensure widely depended upon ESLint related packages stay up to date with newer ESLint releases and doesn't hold the wider community back without depending on one person's GitHub/`npm` account.

Again, totally up to you. I just want you to know we appreciate all you've done and you're welcome to join the organization if you like.

**Comment by ljharb** [comment]
Thanks! I think anything that already has an org is probably ideal to remain there. I would hope that providing backup github/npm access to the community org's leadership would be sufficient to be considered "part of it", including funding, but that can be discussed separately.

**Comment by MichaelDeBoey** [comment]
> I think anything that already has an org is probably ideal to remain there.

As seen in [alternatives](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org#alternatives) of [the '`@eslint-community` GitHub organization' RFC](https://github.com/eslint/rfcs/tree/main/designs/2022-community-eslint-org), people still can have their own org if they want to.

> > The community could independently create multiple more focused organizations to maintain a subset of ESLint related packages.  
> > Some examples of already existing organizations like that are [@import-js](https://github.com/import-js) (which maintains [`eslint-plugin-import`](https://github.com/import-js/eslint-plugin-import)), [@jsx-eslint](https://github.com/jsx-eslint) (which maintains [`eslint-plugin-jsx-a11y`](https://github.com/jsx-eslint/eslint-plugin-jsx-a11y), [`eslint-plugin-react`](https://github.com/jsx-eslint/eslint-plugin-react) & [`jsx-ast-utils`](https://github.com/jsx-eslint/jsx-ast-utils)) & `@standard` (which maintains a couple of [`standard`](https://github.com/standard/standard) related ESLint configs)

> I would hope that providing backup github/npm access to the community org's leadership would be sufficient to be considered "part of it"

If the repo isn't transferred, I don't think it's seen as 'part of the org', but like I said before: it's perfectly fine to have an org by yourself.  
The idea behind my asking is because even though the packages are in an org, they're still reliant on you —@ljharb— for both GitHub & npm.
The new org wants to make sure these awesome ESLint related packages aren't completely lost _if_ something would happen & you can't work on these projects anymore.

> including funding

Packages can keep their sponsoring/funding if they want to.

> > Although packages that are living under the new community org would be allowed to (keep) accept(ing) sponsorship for the maintainer(s) of that package, they should also include the [ESLint Open Collective](https://opencollective.com/eslint) & the [ESLint org](https://github.com/eslint) in their `FUNDING.yml`.

If you have any further questions, just ask away & I'll try to answer them as good as possible.

**Comment by ljharb** [comment]
They’re not reliant solely on me - all of them have multiple owners on github and npm.

**Comment by MichaelDeBoey** [comment]
I'm sorry, I thought it was, as you're the only one mentioned in sponsors & seems to be the only active person working on these repos.

Like I said before: it's totally up to you to join the official community org if you want to.

If you have any other concerns/questions/remarks, please let me know.

**Comment by ljharb** [comment]
Thanks, I appreciate that!

If there were some kind of eslint-community github/npm *account*, i'd be happy to add them to reduce bus factor. In addition, funding is going to be something that eslint always has more of than the ecosystem, so it'd be great if the community is able to accumulate funds _and_ distribute them, to projects in the org or not.

Sounds like I should close these issues for now, but happy to keep discussing.

**Comment by ljharb** [comment]
Right, that's not what I mean - I'm saying that eslint's funding will have more money than our own funding whether we keep both or not, and it'd be nice to keep our own but still receive money from eslint-community.

**Comment by MichaelDeBoey** [comment]
If I'm correct, both @import-js & @jsx-eslint already get sponsored by the main ESLint Collective.
Since there's no separate ESLint community collective, but only the main collective, this wouldn't change a thing for you I think?

**Comment by ljharb** [comment]
Yes, at the moment that's the case. Perhaps I'm being overly optimistic about new sources of funding rolling in for the community :-)

**Comment by MichaelDeBoey** [comment]
As I said: there's no separate ESLint community collective, so all new sources of funding would go to the main collective anyways.
