### ISSUE TITLE
MetaProperty

### ISSUE THREAD

**Issue by jvanriel** [jsx-eslint/jsx-ast-utils#134]
$ eslint src --ext ts,tsx --report-unused-disable-directives --max-warnings 0
The prop value with an expression type of MetaProperty could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this fixed immediately.

**Comment by ljharb** [comment]
Duplicate of #119. If you could comment there with the code that's erroring that'd be most helpful!
