### ISSUE TITLE
Error with AstroShorthandAttribute

### ISSUE THREAD

**Issue by gitZokki** [jsx-eslint/jsx-ast-utils#138]
Hi! 👋 
      
Firstly, thanks for your work on this project! 🙂

Today I used [patch-package](https://github.com/ds300/patch-package) to patch `jsx-ast-utils@3.3.5` for the project I'm working on.

Here is the diff that solved my problem:

```diff
diff --git a/node_modules/jsx-ast-utils/lib/propName.js b/node_modules/jsx-ast-utils/lib/propName.js
index 5057886..cf95c41 100644
--- a/node_modules/jsx-ast-utils/lib/propName.js
+++ b/node_modules/jsx-ast-utils/lib/propName.js
@@ -10,7 +10,7 @@ exports.default = propName;
 function propName() {
   var prop = arguments.length > 0 && arguments[0] !== undefined ? arguments[0] : {};
 
-  if (!prop.type || prop.type !== 'JSXAttribute') {
+  if (!prop.type || (prop.type !== 'JSXAttribute' && prop.type !== 'AstroShorthandAttribute')) {
     throw new Error('The prop must be a JSXAttribute collected by the AST parser.');
   }
 
```

The package I used is 'eslint-plugin-jsx-a11y'

<em>This issue body was [partially generated by patch-package](https://github.com/ds300/patch-package/issues/296).</em>

The problem is, that I can't use the html-Tag with shorthand lang-attr
Its the shorthand from the docs https://docs.astro.build/en/recipes/i18n/

Error:
```html
<html {lang}>
  ...
</html>
```

**Comment by ljharb** [comment]
That seems like Astro is modifying JSX, since that kind of shorthand is not valid syntax. I think the only way for whatever Astro-specific eslint parser to work with the rest of the ecosystem, it’d have to pretend that AST node was a normal non-shorthand one. You may need to file an issue there.

**Comment by gitZokki** [comment]
Ok, sry for this ticket and thank you for the info

**Comment by ljharb** [comment]
Please do link the issue tho, I’d love to follow it.

**Comment by yoyo837** [comment]
@zokkis Hi, can you link to the astro issue? I may have encountered the same problem.
