### ISSUE TITLE
jsx-ast-utils shouldn't bundle redundant files for end users

### ISSUE THREAD

**Issue by mcmxcdev** [jsx-eslint/jsx-ast-utils#140]
According to a check with https://github.com/duniul/clean-modules, the whole `__tests__` folder, files like `.eslintrc` and others are included into `node_modules` for end users.

There is no `.npmignore` file or `files` property in `package.json`, so this seems to be a valid problem.

**Comment by ljharb** [comment]
It’s very intentional to include these files. `npm explore foo && npm install && npm test` should always work.
