### ISSUE TITLE
Unexpected end of JSON input

### ISSUE THREAD

**Issue by THABISANI** [jsx-eslint/jsx-ast-utils#143]
Hello Team

I am getting the error:

1.026 Creating an optimized production build...
12.78 The prop value with an expression type of AwaitExpression could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this fixed immediately.
12.79 The prop value with an expression type of AwaitExpression could not be resolved. Please file an issue ( https://github.com/jsx-eslint/jsx-ast-utils/issues/new ) to get this fixed immediately.
19.24 Failed to compile.
19.24 
19.24 Unexpected end of JSON input
19.24 
19.24 
------
Dockerfile:6
--------------------
   4 |     RUN npm install
   5 |     COPY . .
   6 | >>> RUN npm run build
   7 |     
   8 |     FROM nginx:1.27
--------------------

Below is my docker file:

`
FROM node:23 as build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.27
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html
`

Please help.

**Comment by THABISANI** [comment]
Contents of my package-lock.json:

...
 "jsx-ast-utils": "^3.3.3",
....

**Comment by ljharb** [comment]
I’m not sure why you’re running linting in a build step at all. However, what’s the code it’s failing on?

**Comment by THABISANI** [comment]
Hi, the linting package is a deep dependent of the react-scripts one as can be see below.

% npm ls jsx-ast-utils
<my code package name>
└─┬ react-scripts@5.0.1
  └─┬ eslint-config-react-app@7.0.1
    ├─┬ eslint-plugin-jsx-a11y@6.7.1
    │ └── jsx-ast-utils@3.3.3
    └─┬ eslint-plugin-react@7.32.2
      └── jsx-ast-utils@3.3.3 deduped

Below is by Docker file:

FROM node:23 as build
WORKDIR /app
COPY package*.json .
RUN npm install
COPY . .
RUN npm run build

FROM nginx:1.27
COPY ./nginx/nginx.conf /etc/nginx/nginx.conf
COPY --from=build /app/build /usr/share/nginx/html

**Comment by ljharb** [comment]
Can you try to manually run the linter, locally, and see if that can narrow it down?

**Comment by THABISANI** [comment]
Hi,

Is there a way I can achieve this which is simple like running a command?

**Comment by ljharb** [comment]
Usually it’s `npx eslint .`

**Comment by THABISANI** [comment]
Thank you.

I have managed to see and fix the problem.

I was hrefing a link from an async call.

**Comment by ljharb** [comment]
Can you share what that code was? I'd still like to fix it here.
