### ISSUE TITLE
"The prop value with an expression type of AssignmentExpression could not be resolved."

### ISSUE THREAD

**Issue by notatestuser** [jsx-eslint/jsx-ast-utils#42]
Error trace:
```
The prop value with an expression type of AssignmentExpression could not be resolved.
  Please file issue to get this fixed immediately.
Error: The prop value with an expression type of AssignmentExpression could not be resolved.
  Please file issue to get this fixed immediately.
    at extract (jsx-ast-utils\lib\values\expressions\index.js:175:11)
    at Object.extractValueFromLogicalExpression [as LogicalExpression] (jsx-ast-utils\lib\values\expressions\LogicalExpression.js:28:38)
    at Object.extract [as JSXExpressionContainer] (jsx-ast-utils\lib\values\expressions\index.js:178:21)
    at getValue (jsx-ast-utils\lib\values\index.js:48:27)
    at extractValue (jsx-ast-utils\lib\getPropValue.js:24:12)
    at getPropValue (jsx-ast-utils\lib\getPropValue.js:41:10)
    at eslint-plugin-jsx-a11y\lib\rules\no-static-element-interactions.js:79:95
    at Array.some (native)
    at EventEmitter.JSXOpeningElement (eslint-plugin-jsx-a11y\lib\rules\no-static-element-interactions.js:75:52)
```

After stepping through I've found the culprit in the `onClick` assignment here:
```jsx
this._options.map((config, key) => <DropdownBox.Item key={key}
    onClick={this._cachedOnClickItemHandlers[key] ||
        (this._cachedOnClickItemHandlers[key] = this._onClickItem.bind(null, config))}>
  {config.label}
</DropdownBox.Item>)
```

Yeah, not the nicest code, but I guess this shouldn't break eslint

**Comment by evcohen** [comment]
Oy- will get this added in as soon as possible, thanks for reporting 😄

**Comment by jessebeach** [comment]
@notatestuser , Fixed in version v2.2.1. This will log an error in the console, but it will no longer throw.

**Comment by jessebeach** [comment]
@ljharb are you thinking that jsx-ast-utils should proactively account for these node types?

**Comment by ljharb** [comment]
Absolutely yes. The throw - and the logging - are just the feedback mechanism for how we do that.

**Comment by jessebeach** [comment]
> Absolutely yes. The throw - and the logging - are just the feedback mechanism for how we do that.

That makes sense. I hadn't thought about it that way. Thanks for reopening them.

**Comment by fo-fo** [comment]
Also happens with `+=`, e.g.:
```
let bar = 0;
<div foo={bar += 1} />
```
I found something like this in our codebase that was causing this message. It turned out to be a minor bug (was supposed to be `+`).

Would it be possible to display the file/line where the error happened when this error is logged?
