### ISSUE TITLE
The prop value with an expression type of SequenceExpression could not be resolved. Please file issue to get this fixed immediately.

### ISSUE THREAD

**Issue by chenlulouis** [jsx-eslint/jsx-ast-utils#95]
Hi there,
Looks like there is missing type regarding SequenceExpression, resulting in a error output.
 could you please add it to fix the error? TKS!
var TYPES = {
  Identifier: _Identifier2.default,
  Literal: _Literal2.default,
  JSXElement: _JSXElement2.default,
  TaggedTemplateExpression: _TaggedTemplateExpression2.default,
  TemplateLiteral: _TemplateLiteral2.default,
  ArrowFunctionExpression: _FunctionExpression2.default,
  FunctionExpression: _FunctionExpression2.default,
  LogicalExpression: _LogicalExpression2.default,
  MemberExpression: _MemberExpression2.default,
  OptionalMemberExpression: _OptionalMemberExpression2.default,
  CallExpression: _CallExpression2.default,
  UnaryExpression: _UnaryExpression2.default,
  ThisExpression: _ThisExpression2.default,
  ConditionalExpression: _ConditionalExpression2.default,
  BinaryExpression: _BinaryExpression2.default,
  ObjectExpression: _ObjectExpression2.default,
  NewExpression: _NewExpression2.default,
  UpdateExpression: _UpdateExpression2.default,
  ArrayExpression: _ArrayExpression2.default,
  BindExpression: _BindExpression2.default,
  SpreadElement: _SpreadElement2.default,
  TypeCastExpression: _TypeCastExpression2.default
};

**Comment by ljharb** [comment]
A PR would be welcome.

**Comment by ShubhankarKG** [comment]
Hey @ljharb , I am new here. If you could guide me, that would be great. I'd like to get started here by contributing :)

**Comment by ljharb** [comment]
@ShubhankarKG take a look at https://github.com/jsx-eslint/jsx-ast-utils/tree/master/src/values/expressions - i think you'd need to add a `SequenceExpression` file, and then import it into https://github.com/jsx-eslint/jsx-ast-utils/blob/master/src/values/expressions/index.js. Before doing any of that tho, I'd suggest adding tests somewhere in https://github.com/jsx-eslint/jsx-ast-utils/tree/master/__tests__/src.

**Comment by rrhg** [comment]
Is this fixed ? I was going to try to contribute, but couldn't replicate the issue. `yarn check` gave me no errors. Maybe I'm missing something.
