### ISSUE TITLE
The prop value with an expression type of OptionalCallExpression could not be resolved

### ISSUE THREAD

**Issue by GuiiMoraes** [jsx-eslint/jsx-ast-utils#98]
Until run eslint --fix in my project, I receive this message
Looking at ESLINT github issues, it looks like an error on jsx-ast-utils

The prop value with an expression type of OptionalCallExpression could not be resolved. Please file issue to get this fixed immediately.

```
"eslint": "^6.8.0",
"eslint-config-airbnb": "^18.0.1",
"eslint-config-prettier": "^6.9.0",
"eslint-import-resolver-babel-plugin-root-import": "^1.1.1",
"eslint-plugin-import": "^2.20.0",
"eslint-plugin-import-helpers": "^1.0.2",
"eslint-plugin-jsx-a11y": "^6.2.3",
"eslint-plugin-prettier": "^3.1.2",
"eslint-plugin-react": "^7.18.0",
"eslint-plugin-react-hooks": "^1.7.0",
```

**Comment by ljharb** [comment]
Yes, we'll need to add optional call and chaining, and nullish coalescing, to [this list](https://github.com/evcohen/jsx-ast-utils/blob/121b51d130f9980bf021c72b4fc1bded26559cf5/src/values/expressions/index.js#L24-L47).
